# Setup
title: Nobody
description: Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.
url: https://eli5168.github.io
avatar: /assets/imgs/avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /assets/imgs/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts/
  - eli.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: eli5168
  card: summary
logo: logo.png
social:
  name: Eli Chan
  links:
    - https://twitter.com/eli5168
    - https://github.com/eli5168
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
#google_analytics: UA-000000-0
#google_analytics: G-3EE9DZ7LKV

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Eli Chan
  url: https://github.com/eli5168/
  email: elichan5168@gmail.com
